import Link from "next/link";

const companyPolicies = [
  {
    title: "Data Privacy Policy",
    body: "VerdictAI is committed to protecting the privacy and security of all client information. The platform will only collect data necessary to monitor AI-generated responses related to client products or services. All collected data will be stored securely and used solely for the purpose of analyzing AI-generated recommendations and verifying product accuracy. VerdictAI will not sell, distribute, or share client data with third parties without permission.",
  },
  {
    title: "AI Transparency and Ethics Policy",
    body: "VerdictAI promotes responsible use of artificial intelligence by ensuring that AI-generated information is monitored for accuracy and fairness. The platform is designed to detect hallucinations, misleading product claims, and outdated information generated by AI systems. When inaccuracies are detected, VerdictAI will notify the client and provide recommendations to correct the issue. This policy ensures that businesses maintain transparency and protect consumer trust.",
  },
  {
    title: "Data Accuracy Policy",
    body: "VerdictAI verifies AI-generated product claims by comparing them against verified sources such as manufacturer databases, official product pages, and structured data formats like Schema.org. The system flags inconsistencies in pricing, product specifications, and availability. Clients will receive regular reports highlighting potential inaccuracies so they can update their product information accordingly.",
  },
  {
    title: "Security Policy",
    body: "VerdictAI implements secure data storage and encryption protocols to protect client data from unauthorized access. Access to internal systems will be limited to authorized personnel, and regular security audits will be conducted to maintain system integrity and prevent cyber threats.",
  },
  {
    title: "Compliance Policy",
    body: "VerdictAI operates in accordance with applicable data protection and consumer protection laws. The company will ensure that its technology aligns with responsible AI guidelines and maintains compliance with evolving regulations related to artificial intelligence and digital commerce.",
  },
];

export default function RiskPage() {
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,rgba(59,130,246,0.14),transparent_28%),radial-gradient(circle_at_bottom_right,rgba(16,185,129,0.10),transparent_24%),linear-gradient(180deg,#f8fbff_0%,#eef4ff_100%)] px-4 py-6 text-slate-900 sm:px-6 lg:px-8">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
        <header className="rounded-[2rem] border border-slate-200/80 bg-white/85 p-5 shadow-[0_18px_50px_rgba(15,23,42,0.08)] backdrop-blur sm:p-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-700/70">
                VerdictAI
              </p>
              <h1 className="mt-2 font-display text-4xl text-slate-950">
                Company Policies
              </h1>
              <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600 sm:text-base">
                These policies define how VerdictAI handles privacy, accuracy,
                security, ethics, and compliance while monitoring AI shopping
                answers for clients.
              </p>
            </div>
            <div className="flex flex-wrap gap-3">
              <Link
                href="/"
                className="rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-700"
              >
                Back to Dashboard
              </Link>
              <button
                type="button"
                className="rounded-full bg-slate-100 px-5 py-3 text-sm font-semibold text-slate-700"
              >
                Create Account (Coming Soon)
              </button>
            </div>
          </div>
        </header>

        <section className="rounded-[2rem] border border-slate-200/80 bg-[linear-gradient(135deg,#0f172a,#1e3a8a)] p-7 text-white shadow-[0_28px_70px_rgba(15,23,42,0.18)]">
          <p className="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-blue-100">
            Policy Framework
          </p>
          <h2 className="mt-5 max-w-3xl font-display text-4xl leading-tight">
            Protecting client data, ensuring AI transparency, and supporting
            compliant digital commerce
          </h2>
          <p className="mt-4 max-w-3xl text-sm leading-7 text-slate-200 sm:text-base">
            VerdictAI is built to help businesses monitor AI-generated shopping
            answers responsibly. The policies below replace general compliance
            messaging with the actual framework that governs the product.
          </p>
        </section>

        <section className="rounded-[2rem] border border-slate-200/80 bg-white/80 p-6 shadow-[0_22px_60px_rgba(15,23,42,0.08)] backdrop-blur">
          <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.24em] text-blue-700/70">
                Company Policies
              </p>
              <h2 className="mt-2 font-display text-3xl text-slate-950">
                Core privacy, ethics, security, and compliance standards
              </h2>
            </div>
            <p className="max-w-xl text-sm leading-6 text-slate-500">
              These policies describe how VerdictAI manages client trust and
              operational responsibility across the platform.
            </p>
          </div>

          <div className="mt-6 grid gap-4 lg:grid-cols-2">
            {companyPolicies.map((policy) => (
              <article
                key={policy.title}
                className="rounded-[1.75rem] border border-slate-200 bg-[linear-gradient(180deg,#ffffff,#f8fafc)] p-6 shadow-[0_16px_40px_rgba(15,23,42,0.08)]"
              >
                <p className="text-lg font-semibold text-slate-950">
                  {policy.title}
                </p>
                <p className="mt-4 text-sm leading-7 text-slate-600">
                  {policy.body}
                </p>
              </article>
            ))}
          </div>
        </section>
      </div>
    </main>
  );
}
